import '@/components/site/listing-detail/listing-ask.test'
import '@/components/site/listing-detail/listing-gallery-alt.test'
import '@/components/site/listing-detail/listing-remainder-contract.test'
import '@/components/site/listing-detail/listing-similar.test'
import '@/components/site/listing-detail/listing-fold-actions.test'
import './listing-client-payload.test'
