import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function readSrc(rel: string): string {
  return readFileSync(resolve(rel), 'utf8')
}

describe('SITE-110 search catalog install', () => {
  it('route page and _v3 import the installed catalog files', () => {
    const page = readSrc('app/search/page.tsx')
    const catalog = readSrc('app/search/_v3/search-catalog.ts')
    const command = readSrc('app/search/_v3/SearchCommand.client.tsx')
    const price = readSrc('app/search/_v3/SearchPriceRail.client.tsx')
    const morph = readSrc('app/search/_v3/SearchMorph.client.tsx')
    const sheet = readSrc('app/search/_v3/SearchFiltersSheet.client.tsx')
    const atlas = readSrc('app/search/_v3/SearchAtlas.client.tsx')
    expect(page).toContain("from '@/components/motion/morphing-search'")
    expect(page).toContain("from '@/components/motion/range-slider'")
    expect(page).toContain("from '@/components/ui/command'")
    expect(page).toContain('SearchAtlasPane')
    expect(page).toContain('atlasMap')
    expect(catalog).toContain("from '@/components/motion/morphing-search'")
    expect(catalog).toContain("from '@/components/motion/range-slider'")
    expect(catalog).toContain("from '@/components/ui/command'")
    expect(catalog).toContain('V3Sheet')
    expect(catalog).toContain('V3Atlas')
    expect(command).toContain("from '@/components/ui/command'")
    expect(command).toContain('CommandShortcut')
    expect(command).toContain('No command matches that.')
    expect(price).toContain("from '@/components/motion/range-slider'")
    expect(price).toContain("from '@/components/site/v3/V3Range.logic'")
    expect(price).toContain('snapToStops')
    expect(morph).toContain("from '@/components/motion/morphing-search'")
    expect(morph).toContain('<MorphingSearch')
    expect(morph).not.toMatch(/from ['"]@\/components\/site\/v3['"]/)
    expect(morph).not.toContain('<V3MorphSearch')
    expect(sheet).toContain('V3Sheet')
    expect(sheet).toContain('surface="drawer"')
    expect(sheet).toContain('showProgress={false}')
    expect(sheet).toContain("from '@/components/motion/range-slider'")
    expect(sheet).toContain('<RangeSlider')
    expect(sheet).toContain("kind: 'facts'")
    expect(sheet).toContain("kind: 'select'")
    expect(sheet).not.toContain('How many bedrooms')
    expect(sheet).not.toContain('STEP 1')
    expect(atlas).toContain('<V3Atlas')
  })

  it('search dock does not control MorphingSearch open — the catalog owns the morph', () => {
    const filters = readSrc('components/search/SearchFilters.tsx')
    expect(filters).toContain('SearchMorph')
    expect(filters).not.toContain('V3MorphSearch')
    expect(filters).toContain('SEARCH_PLACE_SEEDS')
    expect(filters).not.toMatch(/open=\{morphOpen\}/)
    expect(filters).toContain('onOpenChange')
    expect(filters).toContain('Search places')
    expect(filters).toContain('morphOpen ? null')
    expect(filters).toContain('catalog portal only')
    expect(filters).toContain('SearchPriceRail')
    expect(filters).toContain('SearchCommand')
    expect(filters).toContain('SearchFiltersSheet')
    expect(filters).not.toContain('AllFiltersSheet')
    expect(filters).toMatch(/srch-chip-rail hidden min-w-0 flex-1 flex-nowrap/)
    expect(filters).not.toMatch(/srch-chip-rail hidden min-w-0 flex-1 flex-nowrap[^>]*(?:sm:flex)/)
  })

  it('catalog sources keep the demo markers', () => {
    const morph = readSrc('components/motion/morphing-search.tsx')
    expect(morph).toContain('aria-haspopup="dialog"')
    expect(morph).toContain('layoutId')
    expect(morph).toContain('backdrop-blur-xl')
    expect(morph).toContain('bg-foreground/40')
    const houseCss = readSrc('components/site/v3/V3MorphSearch.css')
    expect(houseCss).not.toContain('backdrop-filter: none')
    expect(houseCss).not.toContain("[data-v3-morph='panel']")
  })
})
