/**
 * Meta offline-conversion upload — Phase 6 (full-funnel attribution), the
 * closed-loop ROAS piece.
 *
 * When a lead that arrived from a Meta ad (it carried a click id — fbclid, which
 * we persist first-party as fbc on the visitor session / lead) later converts
 * OFFLINE — signs a listing agreement, goes under contract, closes — we upload
 * that conversion back to Meta. The ad that drove the original click gets
 * credited and the campaign can optimize toward real seller/buyer outcomes, not
 * just form fills. Without this, Meta only ever sees the Lead form-fill and
 * optimizes for cheap leads instead of leads that actually transact.
 *
 * Same pixel + token + SHA-256-PII + event_id dedup discipline as the online
 * CAPI path (lib/meta-capi.ts), but tuned for offline:
 *   - action_source 'system_generated' (the conversion did not happen on the site;
 *     it was generated by our CRM/transaction system).
 *   - a HISTORICAL event_time (when the milestone actually happened). NOTE: Meta's
 *     /events endpoint accepts event_time up to 7 days in the past — upload at or
 *     near the milestone, not in a months-later batch (older events are rejected).
 *   - the stored fbc click id is the attribution key back to the ad click.
 *   - SHA-256-hashed PII only (raw email/phone to Meta is a compliance failure).
 *   - LDU passthrough for opted-out leads (CCPA/CPRA), consistent with the pixel.
 *   - an idempotent event_id (derive from lead + milestone) so a re-run / retry
 *     never double-counts the conversion.
 *   - optional test_event_code — routes to the Events Manager Test tab and is
 *     NOT counted as a real conversion (used by the smoke test).
 *
 * Gate: invariants locked by scripts/check-tracking-policy.mjs (G48).
 */
import { createHash } from 'crypto'

const PIXEL_ID = process.env.NEXT_PUBLIC_META_PIXEL_ID?.trim()
const ACCESS_TOKEN = process.env.META_CAPI_ACCESS_TOKEN?.trim()

const sha256 = (v: string): string => createHash('sha256').update(v.trim().toLowerCase()).digest('hex')

/** Conversion milestones we upload, mapped to a Meta standard event name. */
export type OfflineMilestone = 'listing_signed' | 'under_contract' | 'closed' | 'buyer_signed'

const MILESTONE_EVENT: Record<OfflineMilestone, string> = {
  listing_signed: 'Lead', // a signed listing is a qualified, transacting seller lead
  buyer_signed: 'Lead',
  under_contract: 'StartTrial', // mid-funnel signal Meta can optimize toward
  closed: 'Purchase', // the revenue event
}

export type OfflineConversionInput = {
  /** Which transaction milestone converted. Picks the Meta event_name. */
  milestone: OfflineMilestone
  /** Lead email (raw — hashed here). */
  email?: string | null
  /** Lead phone (raw — digits extracted + hashed here). */
  phone?: string | null
  firstName?: string | null
  lastName?: string | null
  /** Stored Meta click id (fbc) from the original ad click — the attribution key. */
  fbc?: string | null
  fbp?: string | null
  /** Conversion value in USD (commission, or the milestone's economic value). */
  value?: number | null
  currency?: string
  /** Unix seconds when the milestone actually happened. Defaults to now. Must be
   *  within ~7 days for Meta's /events endpoint to accept it. */
  eventTimeSec?: number
  /** Stable idempotency key (e.g. `${fubPersonId}:${milestone}`) so retries dedupe. */
  eventId: string
  /** Limited Data Use — pass true for leads who did not grant marketing consent. */
  ldu?: boolean
  /** Test mode — Events Manager Test tab only, NOT a real conversion. */
  testEventCode?: string
}

export type OfflineConversionResult =
  | { ok: true; eventsReceived: number; fbtraceId?: string }
  | { ok: false; error: string }

export async function uploadOfflineConversion(input: OfflineConversionInput): Promise<OfflineConversionResult> {
  if (!PIXEL_ID || !ACCESS_TOKEN) {
    return { ok: false, error: 'META_CAPI_ACCESS_TOKEN or NEXT_PUBLIC_META_PIXEL_ID not set' }
  }
  if (!input.eventId) return { ok: false, error: 'eventId required (idempotency / pixel dedup)' }
  const phoneDigits = input.phone ? input.phone.replace(/\D/g, '') : ''
  // Meta needs at least one strong match key or there is nothing to attribute.
  if (!input.email && !phoneDigits && !input.fbc) {
    return { ok: false, error: 'no match key — need at least one of email / phone / fbc' }
  }

  const userData: Record<string, unknown> = {}
  if (input.email) userData.em = [sha256(input.email)]
  if (phoneDigits) userData.ph = [sha256(phoneDigits)]
  if (input.firstName) userData.fn = [sha256(input.firstName)]
  if (input.lastName) userData.ln = [sha256(input.lastName)]
  if (input.fbc) userData.fbc = input.fbc
  if (input.fbp) userData.fbp = input.fbp

  const event: Record<string, unknown> = {
    event_name: MILESTONE_EVENT[input.milestone],
    event_time: input.eventTimeSec ?? Math.floor(Date.now() / 1000),
    action_source: 'system_generated',
    event_id: input.eventId,
    user_data: userData,
    ...(input.value != null
      ? { custom_data: { value: input.value, currency: input.currency ?? 'USD', milestone: input.milestone } }
      : { custom_data: { milestone: input.milestone } }),
    ...(input.ldu
      ? { data_processing_options: ['LDU'], data_processing_options_country: 0, data_processing_options_state: 0 }
      : {}),
  }

  const body: Record<string, unknown> = { data: [event], access_token: ACCESS_TOKEN }
  if (input.testEventCode) body.test_event_code = input.testEventCode

  let res: Response
  try {
    res = await fetch(`https://graph.facebook.com/v21.0/${PIXEL_ID}/events`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
  } catch (e) {
    return { ok: false, error: `network: ${e instanceof Error ? e.message : String(e)}` }
  }
  const json: { events_received?: number; fbtrace_id?: string; error?: unknown } = await res
    .json()
    .catch(() => ({}))
  if (!res.ok) return { ok: false, error: `${res.status}: ${JSON.stringify(json)}` }
  return { ok: true, eventsReceived: json.events_received ?? 0, fbtraceId: json.fbtrace_id }
}
