'use client'

/** Lucide icon registry for the admin nav + command palette. */
import type { ComponentType } from 'react'
import {
  Activity,
  BadgeCheck,
  BarChart3,
  Building2,
  Camera,
  ClipboardCheck,
  Clock,
  Coins,
  Database,
  DollarSign,
  FileSearch,
  FileText,
  Files,
  Filter,
  Flame,
  FolderOpen,
  Gauge,
  Globe,
  Handshake,
  Home,
  Image,
  Images,
  Inbox,
  Layers,
  LayoutDashboard,
  ListTodo,
  Mail,
  Map,
  MapPin,
  Megaphone,
  PenLine,
  PieChart,
  RefreshCw,
  ScrollText,
  Search,
  Target,
  TrendingUp,
  Trophy,
  User,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Zap,
} from 'lucide-react'
import type { AdminIconName } from '@/app/components/admin/admin-nav'

export const ADMIN_NAV_ICONS: Record<AdminIconName, ComponentType<{ className?: string }>> = {
  dashboard: LayoutDashboard,
  inbox: Inbox,
  flame: Flame,
  'clipboard-check': ClipboardCheck,
  'pen-line': PenLine,
  'list-todo': ListTodo,
  'user-plus': UserPlus,
  users: Users,
  layers: Layers,
  mail: Mail,
  gauge: Gauge,
  handshake: Handshake,
  dollar: DollarSign,
  wallet: Wallet,
  'file-text': FileText,
  home: Home,
  clock: Clock,
  'file-search': FileSearch,
  search: Search,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  megaphone: Megaphone,
  filter: Filter,
  trophy: Trophy,
  coins: Coins,
  'trending-up': TrendingUp,
  globe: Globe,
  'map-pin': MapPin,
  activity: Activity,
  target: Target,
  'badge-check': BadgeCheck,
  map: Map,
  building: Building2,
  files: Files,
  'folder-open': FolderOpen,
  images: Images,
  image: Image,
  camera: Camera,
  refresh: RefreshCw,
  zap: Zap,
  user: User,
  'user-cog': UserCog,
  'scroll-text': ScrollText,
  database: Database,
}
