# GENERATED — DO NOT EDIT. Source of truth: scripts/brand-voice-vocabulary.cjs
# Regenerate: node scripts/gen-brand-voice-consumers.mjs --write
#
# The single mirror of the canonical banned vocabulary for the build_*.py
# producer fleet. Import from here (via scripts/_producer_lib.py) instead of
# hand-typing a list — ci:voice-vocab-parity fails on any drift.

PUNCTUATION_CHARS = ["—", "–", ";", "!"]

BANNED_WORD_STRINGS = [
    "act fast",
    "act now",
    "as you probably know",
    "bespoke",
    "boasts",
    "boutique brokerage",
    "breathtaking",
    "bustling",
    "captivating",
    "charming",
    "curated",
    "delve",
    "don't miss out",
    "dream home",
    "dynamic",
    "eclectic",
    "elevate",
    "entertainer's dream",
    "exquisite",
    "from your local team",
    "get ready to fall in love",
    "gorgeous",
    "guidance from a local team",
    "guidance from your local team",
    "hidden gem",
    "holistic",
    "honest guidance from a local team",
    "honest guidance from your local team",
    "i know this seems complicated",
    "immaculate",
    "just the three of us",
    "let me explain in simple terms",
    "luxurious",
    "luxury concierge",
    "meticulously maintained",
    "must see",
    "must-see",
    "nestled",
    "premier",
    "premier brokerage",
    "pristine",
    "robust",
    "seamless",
    "small brokerage",
    "small business like ours",
    "small team",
    "stunning",
    "stunning new listing",
    "tapestry",
    "team of three",
    "three brokers",
    "top 1 percent",
    "top producing",
    "truly",
    "trusted local team",
    "tucked away",
    "unlock",
    "updated throughout",
    "vibrant",
    "we are passionate about",
    "we pride ourselves on",
    "we will handle everything",
    "what a beautiful home",
    "white glove",
    "won't last",
    "won't last long",
    "you are receiving this because",
    "you have great taste",
    "you may be wondering why",
    "you won't believe",
    "you're receiving this because",
    "your real estate journey",
    "your trusted",
]

BANNED_WORDS = [
    {"word": "act fast", "category": "fake urgency"},
    {"word": "act now", "category": "fake urgency"},
    {"word": "as you probably know", "category": "pandering"},
    {"word": "bespoke", "category": "AI filler"},
    {"word": "boasts", "category": "real-estate cliché"},
    {"word": "boutique brokerage", "category": "marketing slop"},
    {"word": "boutique brokerage", "category": "smallness positioning"},
    {"word": "breathtaking", "category": "real-estate cliché"},
    {"word": "bustling", "category": "AI filler"},
    {"word": "captivating", "category": "real-estate cliché"},
    {"word": "charming", "category": "real-estate cliché"},
    {"word": "curated", "category": "AI filler"},
    {"word": "delve", "category": "AI filler"},
    {"word": "don't miss out", "category": "fake urgency"},
    {"word": "dream home", "category": "real-estate cliché"},
    {"word": "dynamic", "category": "AI filler"},
    {"word": "eclectic", "category": "AI filler"},
    {"word": "elevate", "category": "AI filler"},
    {"word": "entertainer's dream", "category": "real-estate cliché"},
    {"word": "exquisite", "category": "real-estate cliché"},
    {"word": "from your local team", "category": "marketing slop"},
    {"word": "get ready to fall in love", "category": "hype opening"},
    {"word": "gorgeous", "category": "real-estate cliché"},
    {"word": "guidance from a local team", "category": "marketing slop"},
    {"word": "guidance from your local team", "category": "marketing slop"},
    {"word": "hidden gem", "category": "real-estate cliché"},
    {"word": "holistic", "category": "AI filler"},
    {"word": "honest guidance from a local team", "category": "marketing slop"},
    {"word": "honest guidance from your local team", "category": "marketing slop"},
    {"word": "i know this seems complicated", "category": "pandering"},
    {"word": "immaculate", "category": "real-estate cliché"},
    {"word": "just the three of us", "category": "smallness positioning"},
    {"word": "let me explain in simple terms", "category": "pandering"},
    {"word": "luxurious", "category": "real-estate cliché"},
    {"word": "luxury concierge", "category": "marketing slop"},
    {"word": "meticulously maintained", "category": "real-estate cliché"},
    {"word": "must see", "category": "real-estate cliché"},
    {"word": "must-see", "category": "real-estate cliché"},
    {"word": "nestled", "category": "real-estate cliché"},
    {"word": "premier", "category": "marketing slop"},
    {"word": "premier brokerage", "category": "marketing slop"},
    {"word": "pristine", "category": "real-estate cliché"},
    {"word": "robust", "category": "AI filler"},
    {"word": "seamless", "category": "AI filler"},
    {"word": "small brokerage", "category": "smallness positioning"},
    {"word": "small business like ours", "category": "smallness positioning"},
    {"word": "small team", "category": "smallness positioning"},
    {"word": "stunning", "category": "real-estate cliché"},
    {"word": "stunning new listing", "category": "hype opening"},
    {"word": "tapestry", "category": "AI filler"},
    {"word": "team of three", "category": "smallness positioning"},
    {"word": "three brokers", "category": "smallness positioning"},
    {"word": "top 1 percent", "category": "marketing slop"},
    {"word": "top producing", "category": "marketing slop"},
    {"word": "truly", "category": "real-estate cliché"},
    {"word": "trusted local team", "category": "marketing slop"},
    {"word": "tucked away", "category": "real-estate cliché"},
    {"word": "unlock", "category": "AI filler"},
    {"word": "updated throughout", "category": "real-estate cliché"},
    {"word": "vibrant", "category": "AI filler"},
    {"word": "we are passionate about", "category": "marketing slop"},
    {"word": "we pride ourselves on", "category": "marketing slop"},
    {"word": "we will handle everything", "category": "pandering"},
    {"word": "what a beautiful home", "category": "pandering"},
    {"word": "white glove", "category": "marketing slop"},
    {"word": "won't last", "category": "fake urgency"},
    {"word": "won't last long", "category": "fake urgency"},
    {"word": "you are receiving this because", "category": "pandering"},
    {"word": "you have great taste", "category": "pandering"},
    {"word": "you may be wondering why", "category": "pandering"},
    {"word": "you won't believe", "category": "hype opening"},
    {"word": "you're receiving this because", "category": "pandering"},
    {"word": "your real estate journey", "category": "marketing slop"},
    {"word": "your trusted", "category": "marketing slop"},
]
