/**
 * scripts/stat-tables.cjs — the ONE definition of "this is a statistic".
 *
 * Matt, 2026-08-26: "all stats shoule come through one process, enforce this."
 * And, on the first version of this: "if you're inventing things when we've
 * already gone through a process to create them, there should be one single
 * process for creating statistics."
 *
 * He is right, and the first version got it wrong. It hand-typed a list of
 * stat-bearing tables into .claude/hooks/pre-tool-use.mjs, hand-typed a SECOND
 * copy into scripts/check-script-stat-source.mjs, and invented a 28-table
 * "plumbing" allowlist on top. Three hand-kept artifacts, all of them my
 * judgment rather than anything the repo already knew, all free to drift
 * apart. This file replaces all three.
 *
 * -- THE DEFINITION --------------------------------------------------------
 * Stats come from the DAL. docs/DAL_INDEX.md is auto-generated by G16 and
 * already lists every table the DAL covers. So:
 *
 *     a STAT  =  an aggregate over a table the DAL covers.
 *
 * That is the whole rule. It needs no curated list, because the list already
 * exists and is regenerated from the code; a table added to the DAL is covered
 * the day it lands. There is no exemption set: an aggregate either goes
 * through the DAL or it does not happen. `-- audit:` still licenses a targeted
 * ROW read, which is what it was always for.
 *
 * Same shape as scripts/brand-voice-vocabulary.cjs: one .cjs that both the
 * runtime hook and the CI gate require(), so they cannot disagree.
 */

const { readFileSync } = require('node:fs')
const { join } = require('node:path')

/**
 * Every table a DAL function reads, parsed from the generated index.
 * Returns an empty Set if the index cannot be read - callers decide what that
 * means for them (the hook falls through to its other refusals rather than
 * blocking every query on a missing doc).
 */
function getDalCoveredTables(projectRoot) {
  try {
    const md = readFileSync(join(projectRoot, 'docs/DAL_INDEX.md'), 'utf8')
    const tables = new Set()
    for (const m of md.matchAll(/^\*\*Tables:\*\* (.+)$/gm)) {
      for (const tok of m[1].split(',')) {
        const name = tok.trim().replace(/^`|`$/g, '')
        if (name) tables.add(name)
      }
    }
    return tables
  } catch {
    return new Set()
  }
}

/**
 * Aggregate functions that produce a STATISTIC. Each requires a following
 * paren, so column names like `max_price` and `sold_count` are not matches.
 * The collection aggregates (array_agg / string_agg / json_agg) gather rows
 * into a list rather than measuring anything, so they are not here.
 */
const AGGREGATE_RE =
  /\b(count|sum|avg|min|max|median|mode|stddev|stddev_pop|stddev_samp|variance|var_pop|var_samp|percentile_cont|percentile_disc|corr)\s*\(/i

const GROUP_BY_RE = /\bgroup\s+by\b/i

/** Strip comments so an `-- audit:` reason is neither a trigger nor a hiding place. */
function stripSqlComments(sql) {
  return sql.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/--[^\n]*/g, ' ')
}

/**
 * Does this SQL aggregate over a DAL-covered table? Returns the table name, or
 * null. FROM and JOIN both count: a table pulled in through a join is still
 * inside the measured window.
 */
function sqlAggregatesDalTable(sql, dalTables) {
  const bare = stripSqlComments(String(sql).toLowerCase())
  if (!AGGREGATE_RE.test(bare) && !GROUP_BY_RE.test(bare)) return null
  for (const m of bare.matchAll(
    /\b(?:from|join)\s+(?:only\s+)?(?:public\.)?"?([a-z_][a-z_0-9]*)"?/g,
  )) {
    if (dalTables.has(m[1])) return m[1]
  }
  return null
}

module.exports = {
  getDalCoveredTables,
  sqlAggregatesDalTable,
  stripSqlComments,
  AGGREGATE_RE,
  GROUP_BY_RE,
}
