#!/usr/bin/env sh
# worktree-setup.sh — make a fresh `git worktree add` safe to work and push from.
#
# Three things a new worktree lacks, each of which fails in a different and
# non-obvious way:
#
#   node_modules  — gitignored. Absent, `npx tsc` silently resolves to the bogus
#                   npm package `tsc@2.0.4`, prints nothing and EXITS 0, so a
#                   typecheck that verified nothing looks green. A symlink is
#                   NOT a fix: Turbopack refuses a node_modules resolving
#                   outside the project root. APFS clone (cp -Rc) is
#                   copy-on-write, so it costs ~30s and almost no real disk.
#
#   .env.local    — gitignored. Absent, the production build dies in static
#                   generation on missing NEXT_PUBLIC_SUPABASE_* vars.
#
#   .husky/_      — generated by husky at install time, gitignored. Absent,
#                   core.hooksPath (the RELATIVE path .husky/_) resolves to
#                   nothing, git runs no hooks, and a push skips the entire gate
#                   chain and the production build while still succeeding.
#                   Enforced by scripts/check-hooks-installed.mjs.
#
# usage: sh scripts/worktree-setup.sh [path-to-main-checkout]

set -e
MAIN="${1:-$HOME/RyanRealty}"
TOP="$(git rev-parse --show-toplevel)"

if [ "$TOP" = "$MAIN" ]; then
  echo "worktree-setup: already in the main checkout, nothing to do."
  exit 0
fi

echo "worktree-setup: $TOP  (source: $MAIN)"

if [ ! -x "$TOP/node_modules/.bin/tsc" ]; then
  echo "  node_modules: APFS clone from $MAIN …"
  rm -f "$TOP/node_modules" 2>/dev/null || true
  cp -Rc "$MAIN/node_modules" "$TOP/node_modules"
else
  echo "  node_modules: present"
fi

if [ ! -f "$TOP/.env.local" ]; then
  echo "  .env.local: copying"
  cp "$MAIN/.env.local" "$TOP/.env.local"
else
  echo "  .env.local: present"
fi

if [ ! -f "$TOP/.husky/_/pre-push" ]; then
  echo "  .husky/_: installing hooks"
  cp -R "$MAIN/.husky/_" "$TOP/.husky/_"
else
  echo "  .husky/_: present"
fi

echo "worktree-setup: verifying"
node "$TOP/scripts/check-hooks-installed.mjs"
echo "worktree-setup: ready — this tree can typecheck, build, and push gated."
