-- Deals §10 (docs/fub-crm-spec/10-deals-pipelines.md) — DB-backed pipeline/stage
-- config + multi-contact junction + actual close date.
--
-- 1. crm_pipelines / crm_deal_stages (§20.1/§20.2): until now the Kanban's stage
--    columns were a static module (lib/crm/deal-pipelines.ts mirroring the FUB
--    api-export). §9 Manage Pipelines + §10 Add-a-stage require the config to be
--    MUTABLE (owner-only), so it moves into tables, seeded byte-for-byte from
--    docs/fub-crm-spec/api-export/pipelines.json (same ids, names, colors,
--    orderWeights, closedStage flags). crm_deals.pipeline/.stage stay free text
--    matching these names verbatim (the live rows already do).
-- 2. crm_deal_people (§20.4): a deal can carry MULTIPLE contacts (co-buyers,
--    husband+wife sellers) — the single crm_deals.person_id can't. Backfilled
--    from the existing person_id links; person_id is retained as the legacy
--    primary-contact pointer (scope checks still honor it).
-- 3. crm_deals.actual_close_date (§20.10): FUB's model overloads close_date as
--    both projected and actual. The in-house build records the actual close
--    separately; auto-populated when a deal moves into an is_closed_stage stage.
--
-- Access model: service-role only (RLS enabled, no public policies) — same as
-- every other crm_* table. Broker scoping happens in the DAL/actions layer.

create table if not exists public.crm_pipelines (
  id           bigint generated by default as identity primary key,
  name         text not null unique,
  description  text,
  order_weight integer not null default 1000,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists public.crm_deal_stages (
  id              bigint generated by default as identity primary key,
  pipeline_id     bigint not null references public.crm_pipelines(id) on delete cascade,
  name            text not null,
  color           text not null default '#819cff',
  order_weight    integer not null default 1000,
  is_closed_stage boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (pipeline_id, name)
);

-- Seed = docs/fub-crm-spec/api-export/pipelines.json (authoritative FUB export).
insert into public.crm_pipelines (id, name, description, order_weight) values
  (1, 'Buyers',  'A pipeline for buyers',  1000),
  (2, 'Sellers', 'A pipeline for sellers', 2000)
on conflict (id) do nothing;

insert into public.crm_deal_stages (id, pipeline_id, name, color, order_weight, is_closed_stage) values
  (47, 1, 'Start (temp stage)', '#F3B942', 1000, false),
  (19, 1, 'Buyer Contract',     '#ffad81', 2000, false),
  (21, 1, 'Offer',              '#819cff', 3000, false),
  (23, 1, 'Pending',            '#ffcc44', 4000, false),
  (25, 1, 'Closed',             '#4ad09f', 5000, true),
  (39, 1, 'Lost',               '#ff8181', 6000, false),
  (48, 2, 'Start (temp stage)', '#F3B942', 1000, false),
  (49, 2, 'Pre-Listing',        '#819cff', 2000, false),
  (20, 2, 'Listed',             '#ffad81', 3000, false),
  (22, 2, 'Offer',              '#819cff', 4000, false),
  (24, 2, 'Pending',            '#ffcc44', 5000, false),
  (26, 2, 'Closed',             '#4ad09f', 6000, true),
  (28, 2, 'Lost / Terminated',  '#ff8181', 7000, false)
on conflict (id) do nothing;

-- The seeds used explicit FUB ids; advance the identity sequences past them.
select setval(pg_get_serial_sequence('public.crm_pipelines', 'id'),
              (select coalesce(max(id), 1) from public.crm_pipelines));
select setval(pg_get_serial_sequence('public.crm_deal_stages', 'id'),
              (select coalesce(max(id), 1) from public.crm_deal_stages));

-- §20.4 multi-contact junction.
create table if not exists public.crm_deal_people (
  id         bigint generated by default as identity primary key,
  deal_id    bigint not null references public.crm_deals(id) on delete cascade,
  person_id  bigint not null references public.crm_people(id) on delete cascade,
  role       text,
  created_at timestamptz not null default now(),
  unique (deal_id, person_id)
);
create index if not exists crm_deal_people_person_idx on public.crm_deal_people (person_id);

-- Backfill: every existing single-contact link becomes a junction row.
insert into public.crm_deal_people (deal_id, person_id)
select d.id, d.person_id
from public.crm_deals d
where d.person_id is not null
  and exists (select 1 from public.crm_people p where p.id = d.person_id)
on conflict (deal_id, person_id) do nothing;

-- §20.10 actual close date (in-house extension beyond the FUB baseline).
alter table public.crm_deals add column if not exists actual_close_date date;

-- Backfill: deals already sitting in a closed stage adopt their close_date.
update public.crm_deals d
set actual_close_date = d.close_date
from public.crm_deal_stages s
join public.crm_pipelines p on p.id = s.pipeline_id
where d.actual_close_date is null
  and d.close_date is not null
  and s.is_closed_stage = true
  and d.pipeline = p.name
  and d.stage = s.name;

alter table public.crm_pipelines enable row level security;
alter table public.crm_deal_stages enable row level security;
alter table public.crm_deal_people enable row level security;

comment on table public.crm_pipelines is
  'Deal pipeline config (§10/§20.1). Seeded from the FUB api-export; owner-managed via Manage Pipelines. Service-role access only.';
comment on table public.crm_deal_stages is
  'Per-pipeline Kanban stage config (§20.2): name, accent color, order, is_closed_stage (gates leaderboard/commission reporting). Service-role access only.';
comment on table public.crm_deal_people is
  'Deal ↔ contact junction (§20.4) — multi-contact deals (co-buyers, couples). Service-role access only.';
