-- Blog SEO titles fit the 60-char SERP width (Matt 2026-10-05, "shorten them now").
-- The layout appends " | Ryan Realty" (14 chars), so each seo_title is held to 46
-- (TITLE_BUDGET in lib/site/page-metadata.ts). The live audit found 28 of 29 sampled
-- posts over 60. Each new title keeps the place and the main keyword first, drops a
-- stale year (2024, 2025) and the dollar and unit counts, and adds no figure. To revert, run the
-- REVERT block at the end of this file.

update public.blog_posts as b set seo_title = v.seo_title, updated_at = b.updated_at
from (values
  ('arts-culture-central-oregon', 'Arts and Culture in Central Oregon'),
  ('awbrey-glen-median-price-hoa-dues-2026', 'Awbrey Glen Homes: Prices and HOA Dues'),
  ('bend-approves-new-sdc-methodology', 'Bend Approves New SDC Methodology'),
  ('bend-building-permit-timeline-construction', 'How Long Do Building Permits Take in Bend?'),
  ('bend-infrastructure-water-sewer-roads-growth', 'Bend Infrastructure: Water, Sewer and Roads'),
  ('bend-juniper-ridge-homelessness-housing-strategy', 'Bend''s Juniper Ridge Housing Strategy'),
  ('bend-new-growth-plan-housing-20-years', 'Bend''s Housing Target, Explained'),
  ('bend-oregon-market-report-july-2026', 'Bend Oregon Market Report, July 2026'),
  ('bend-oregon-market-report-june-2026', 'Bend Oregon Market Report, June 2026'),
  ('bend-oregon-market-report-september-2026', 'Bend Oregon Market Report, September 2026'),
  ('bend-vs-redmond-vs-sisters', 'Bend vs Redmond vs Sisters: Which Town Fits?'),
  ('best-neighborhoods-bend-families', 'Best Neighborhoods in Bend for Families'),
  ('best-neighborhoods-bend-retirees', 'Neighborhoods in Bend for Retirees'),
  ('best-time-to-buy-home-central-oregon', 'Best Time to Buy a Home in Central Oregon'),
  ('best-time-to-sell-home-central-oregon', 'Best Time to Sell a Home in Central Oregon'),
  ('black-butte-ranch-guide', 'Black Butte Ranch: Costs, HOA Fees, Rentals'),
  ('brasada-ranch-central-oregon', 'Brasada Ranch: Full-Time Home or Rental?'),
  ('broken-top-bend-golf-community', 'Broken Top Bend: Is Golf Membership Worth It?'),
  ('building-equity-shifting-market', 'Building Home Equity in Central Oregon'),
  ('buyers-agent-bend-buyer-broker-agreement', 'Buyer-Broker Agreements in Bend, Oregon'),
  ('buying-vs-renting-bend-analysis', 'Buying vs Renting in Bend: The 2026 Math'),
  ('caldera-springs-buyers-guide', 'Caldera Springs Buyer''s Guide, Sunriver'),
  ('central-oregon-market-report-july-2026', 'Central Oregon Market Report, July 2026'),
  ('central-oregon-real-estate-investment', 'Is Central Oregon a Good Investment in 2026?'),
  ('closing-costs-buyers-bend-oregon', 'Closing Costs for Buyers in Bend, Oregon'),
  ('cost-of-living-bend-oregon', 'Cost of Living in Bend, Oregon (2026)'),
  ('cost-to-sell-house-bend-oregon', 'Cost to Sell a House in Bend, Oregon'),
  ('crooked-river-ranch-rural-acreage-wells-septic', 'Crooked River Ranch: Acreage, Wells, Septic'),
  ('crosswater-one-home-sold-in-12-months', 'Crosswater Real Estate: What Buying Costs'),
  ('deschutes-county-wildfire-building-codes', 'Wildfire Codes and Defensible Space in Bend'),
  ('dining-craft-beer-bend', 'Dining and Craft Beer in Bend, Oregon'),
  ('eagle-crest-affordable-resort-redmond', 'Eagle Crest Redmond: Affordable Resort Homes'),
  ('fed-rate-decisions-mortgage-rates', 'How Mortgage Rates Are Set: Fed and 10-Year'),
  ('first-time-home-buyer-guide-central-oregon', 'First-Time Buyer Guide: Bend, Central Oregon'),
  ('four-seasons-central-oregon-living', 'Four Seasons of Central Oregon Living'),
  ('getting-around-central-oregon-transportation', 'Getting Around Central Oregon'),
  ('hoa-guide-central-oregon', 'Central Oregon HOA Guide: Fees and CC&Rs'),
  ('home-inspection-checklist-oregon-buyers', 'Home Inspection Checklist for Oregon Buyers'),
  ('home-renovations-add-value-central-oregon', 'Renovations That Add Value in Central Oregon'),
  ('home-staging-tips-central-oregon', 'Home Staging Tips for Central Oregon Sellers'),
  ('how-to-choose-the-right-mortgage', 'Choosing a Mortgage in Central Oregon (2026)'),
  ('how-to-sell-your-home-bend', 'How to Sell Your House in Bend, Oregon'),
  ('inn-of-the-7th-mountain-second-home-or-rental', 'Inn of the 7th Mountain: Home or Rental?'),
  ('insurance-guide-central-oregon-homeowners', 'Homeowners Insurance in Central Oregon'),
  ('interest-rate-changes-home-affordability', 'How Mortgage Rates Change a Bend Payment'),
  ('is-now-a-good-time-to-buy-in-bend', 'Is Now a Good Time to Buy a Home in Bend?'),
  ('la-pine-oregon-market-report-july-2026', 'La Pine Oregon Market Report, July 2026'),
  ('living-in-nw-crossing-bend', 'NW Crossing in Bend: Cost of Walkable Living'),
  ('middle-housing-reshaping-bend-neighborhoods', 'Middle Housing Is Reshaping Bend Neighborhoods'),
  ('moving-to-bend-from-california', 'Moving to Bend from California: What Changes'),
  ('moving-to-bend-relocation-guide', 'Moving to Bend, Oregon: Relocation Guide'),
  ('moving-to-redmond-oregon-guide', 'Moving to Redmond, Oregon: A Practical Guide'),
  ('moving-to-sisters-oregon-guide', 'Moving to Sisters, Oregon: What to Expect'),
  ('national-economic-policy-central-oregon', 'How Federal Policy Reaches Central Oregon'),
  ('outdoor-recreation-central-oregon-homebuyer', 'Outdoor Recreation in Central Oregon'),
  ('preparing-home-for-sale-checklist', 'Pre-Listing Checklist: Central Oregon Sellers'),
  ('price-per-sqft-trends-central-oregon', 'Price Per Square Foot in Central Oregon'),
  ('property-taxes-deschutes-county', 'Property Taxes in Bend and Deschutes County'),
  ('raising-kids-bend-parents-guide', 'Kids in Bend: Parks, Schools, Child Care'),
  ('rate-lock-effect-housing-supply', 'The Rate Lock-In Effect and Bend Housing'),
  ('redmond-oregon-market-report-august-2026', 'Redmond Oregon Market Report, August 2026'),
  ('redmond-oregon-market-report-july-2026', 'Redmond Oregon Market Report, July 2026'),
  ('redmond-oregon-market-report-september-2026', 'Redmond Oregon Market Report, September 2026'),
  ('retirement-central-oregon', 'Why Retirees Choose Central Oregon'),
  ('schools-central-oregon-guide-families', 'Schools in Central Oregon: A Family Guide'),
  ('second-home-vs-investment-property', 'Second Home vs Investment Property (2026)'),
  ('senate-bill-1537-bend-ugb-expansion', 'Senate Bill 1537 and Bend''s UGB Expansion'),
  ('sisters-oregon-market-report-july-2026', 'Sisters Oregon Market Report, July 2026'),
  ('sunriver-oregon-market-report-july-2026', 'Sunriver Oregon Market Report, July 2026'),
  ('sunriver-year-round-living-vs-vacation', 'Sunriver Year-Round Living: What It Costs'),
  ('tetherow-resort-living-real-estate', 'Tetherow, Bend: Resort Golf Community Guide'),
  ('understanding-earnest-money-oregon', 'Earnest Money in Oregon Real Estate'),
  ('understanding-home-appraisals', 'Home Appraisals in Central Oregon'),
  ('understanding-months-of-supply', 'Months of Supply Explained: Central Oregon'),
  ('vacation-rental-rules-bend-deschutes', 'Bend Vacation Rental Rules, Deschutes County'),
  ('vandevert-ranch-one-home-sold-in-12-months', 'Vandevert Ranch: One Sale in 12 Months'),
  ('westside-vs-eastside-bend', 'Westside vs Eastside Bend: The Trade-offs'),
  ('what-happens-between-offer-accepted-and-closing', 'What Happens Between Offer and Closing'),
  ('widgi-creek-condo-or-house-what-it-costs', 'Widgi Creek: Condo or House, What Each Costs'),
  ('working-remote-central-oregon', 'Working Remote from Central Oregon')
) as v(slug, seo_title)
where b.slug = v.slug;

-- REVERT: the seo_title values this replaced, read 2026-10-05 before the update.
-- update public.blog_posts as b set seo_title = v.seo_title, updated_at = b.updated_at from (values
--   ('arts-culture-central-oregon', 'Arts and Culture Scene in Central Oregon Full Guide'),
--   ('awbrey-glen-median-price-hoa-dues-2026', 'Awbrey Glen Homes: $1,349,000 Median in 2026'),
--   ('bend-approves-new-sdc-methodology', 'Bend City Council Approves Tiered SDC Methodology 2024'),
--   ('bend-building-permit-timeline-construction', 'How Long Do Building Permits Take in Bend? 2026 Timeline'),
--   ('bend-infrastructure-water-sewer-roads-growth', 'Bend Infrastructure Challenge for Water Sewer and Roads'),
--   ('bend-juniper-ridge-homelessness-housing-strategy', 'Bend Juniper Ridge Homelessness and Housing Strategy'),
--   ('bend-new-growth-plan-housing-20-years', 'Bend''s Housing Target: 34,116 Units and What It Means'),
--   ('bend-oregon-market-report-july-2026', 'Bend Oregon Market Report July 2026: Prices and Inventory'),
--   ('bend-oregon-market-report-june-2026', 'Bend Oregon Market Report June 2026: Prices and Inventory'),
--   ('bend-oregon-market-report-september-2026', 'Bend Oregon Housing Market Report, September 2026'),
--   ('bend-vs-redmond-vs-sisters', 'Bend vs Redmond vs Sisters: Which Central Oregon Town Fits?'),
--   ('best-neighborhoods-bend-families', 'Best Neighborhoods in Bend Oregon for Families 2025'),
--   ('best-neighborhoods-bend-retirees', 'Neighborhoods in Bend for Retirees (2026 Guide)'),
--   ('best-time-to-buy-home-central-oregon', 'Best Time to Buy a Home in Central Oregon 2025'),
--   ('best-time-to-sell-home-central-oregon', 'Best Time to Sell Your Home in Central Oregon | 2025'),
--   ('black-butte-ranch-guide', 'Black Butte Ranch: Costs, HOA Fees, and Rental Rules'),
--   ('brasada-ranch-central-oregon', 'Brasada Ranch: Full-Time Home or Rental? The Costs to Know'),
--   ('broken-top-bend-golf-community', 'Broken Top in Bend: Is the Golf Membership Worth It?'),
--   ('building-equity-shifting-market', 'Building Home Equity in Central Oregon: Market vs Loan (2026)'),
--   ('buyers-agent-bend-buyer-broker-agreement', 'Buyer-Broker Agreements in Bend, Oregon: How Agents Get Paid'),
--   ('buying-vs-renting-bend-analysis', 'Buying vs Renting in Bend, Oregon: The 2026 Math'),
--   ('caldera-springs-buyers-guide', 'Caldera Springs Resort Buyers Guide Sunriver Oregon'),
--   ('central-oregon-market-report-july-2026', 'Central Oregon Market Report July 2026: A Regional Shift'),
--   ('central-oregon-real-estate-investment', 'Is Central Oregon a Good Real Estate Investment? 2026 Math'),
--   ('closing-costs-buyers-bend-oregon', 'Closing Costs for Buyers in Bend, Oregon (2026)'),
--   ('cost-of-living-bend-oregon', 'Cost of Living in Bend, Oregon (2026): Housing, Taxes'),
--   ('cost-to-sell-house-bend-oregon', 'Cost to Sell a House in Bend, Oregon: Fees, Title, Closing'),
--   ('crooked-river-ranch-rural-acreage-wells-septic', 'Crooked River Ranch: Ready for a Well and Septic?'),
--   ('crosswater-one-home-sold-in-12-months', 'Crosswater Real Estate: 1 Sale in 12 Months, Explained'),
--   ('deschutes-county-wildfire-building-codes', 'Wildfire Building Codes and Defensible Space in Bend (2026)'),
--   ('dining-craft-beer-bend', 'Dining and Craft Beer Scene in Bend Oregon Guide'),
--   ('eagle-crest-affordable-resort-redmond', 'Eagle Crest in Redmond: Resort Homes From $385K (2026)'),
--   ('fed-rate-decisions-mortgage-rates', 'How Mortgage Rates Are Set: Fed, 10-Year Treasury, Spread'),
--   ('first-time-home-buyer-guide-central-oregon', 'First-Time Home Buyer Guide: Bend and Central Oregon (2026)'),
--   ('four-seasons-central-oregon-living', 'Four Seasons of Central Oregon Living What to Expect'),
--   ('getting-around-central-oregon-transportation', 'Getting Around Central Oregon Transportation Guide'),
--   ('hoa-guide-central-oregon', 'Central Oregon HOA Guide (2026): Fees, CC&Rs, Resale Impact'),
--   ('home-inspection-checklist-oregon-buyers', 'Home Inspection Checklist for Oregon Home Buyers'),
--   ('home-renovations-add-value-central-oregon', 'Home Renovations That Add Value in Central Oregon (2026)'),
--   ('home-staging-tips-central-oregon', 'Home Staging Tips for Central Oregon Sellers | 2025'),
--   ('how-to-choose-the-right-mortgage', 'Choosing a Mortgage in Central Oregon: 2026 Limits and Fees'),
--   ('how-to-sell-your-home-bend', 'How to Sell Your House in Bend, Oregon | Step by Step'),
--   ('inn-of-the-7th-mountain-second-home-or-rental', 'Inn of the 7th Mountain: Second Home or Rental Unit?'),
--   ('insurance-guide-central-oregon-homeowners', 'Homeowners Insurance in Central Oregon: Wildfire, FAIR Plan'),
--   ('interest-rate-changes-home-affordability', 'How Mortgage Rates Change a Bend Home Payment (2026)'),
--   ('is-now-a-good-time-to-buy-in-bend', 'Is Now a Good Time to Buy a Home in Bend, Oregon?'),
--   ('la-pine-oregon-market-report-july-2026', 'La Pine Oregon Market Report July 2026: Prices and Supply'),
--   ('living-in-nw-crossing-bend', 'NW Crossing in Bend: What Walkable Living Costs'),
--   ('middle-housing-reshaping-bend-neighborhoods', 'Middle Housing Is Slowly Reshaping Bend Neighborhoods'),
--   ('moving-to-bend-from-california', 'Moving to Bend from California: Taxes, Housing, and Timing'),
--   ('moving-to-bend-relocation-guide', 'Moving to Bend Oregon: Realistic Relocation Guide 2025'),
--   ('moving-to-redmond-oregon-guide', 'Moving to Redmond Oregon: Practical Relocation Guide'),
--   ('moving-to-sisters-oregon-guide', 'Moving to Sisters Oregon: What to Expect When You Move'),
--   ('national-economic-policy-central-oregon', 'How Federal Policy Reaches Central Oregon Real Estate (2026)'),
--   ('outdoor-recreation-central-oregon-homebuyer', 'Outdoor Recreation in Central Oregon for Homebuyers'),
--   ('preparing-home-for-sale-checklist', 'Pre Listing Checklist for Central Oregon Home Sellers'),
--   ('price-per-sqft-trends-central-oregon', 'Price Per Square Foot in Central Oregon: June 2026 Data'),
--   ('property-taxes-deschutes-county', 'Property Taxes in Bend and Deschutes County (2026)'),
--   ('raising-kids-bend-parents-guide', 'Kids in Bend: Parks, Schools, Child Care, and Seasons'),
--   ('rate-lock-effect-housing-supply', 'The Rate Lock-In Effect and Bend Housing Supply (2026)'),
--   ('redmond-oregon-market-report-august-2026', 'Redmond Oregon Housing Market Report, August 2026'),
--   ('redmond-oregon-market-report-july-2026', 'Redmond Oregon Market Report July 2026: Prices and Supply'),
--   ('redmond-oregon-market-report-september-2026', 'Redmond Oregon Housing Market Report, September 2026'),
--   ('retirement-central-oregon', 'Retirement in Central Oregon Why Retirees Choose It'),
--   ('schools-central-oregon-guide-families', 'Schools in Central Oregon: Districts, Charters, Private (2026)'),
--   ('second-home-vs-investment-property', 'Second Home vs Investment Property: 2026 Tax Tests'),
--   ('senate-bill-1537-bend-ugb-expansion', 'Senate Bill 1537 UGB Expansion Opportunity for Bend OR'),
--   ('sisters-oregon-market-report-july-2026', 'Sisters Oregon Market Report July 2026: Prices and Supply'),
--   ('sunriver-oregon-market-report-july-2026', 'Sunriver Oregon Market Report July 2026: Prices and Supply'),
--   ('sunriver-year-round-living-vs-vacation', 'Sunriver Year-Round Living: What It Costs in 2026'),
--   ('tetherow-resort-living-real-estate', 'Tetherow Bend Oregon Resort Golf Community Buyer Guide'),
--   ('understanding-earnest-money-oregon', 'Understanding Earnest Money in Oregon Real Estate'),
--   ('understanding-home-appraisals', 'Understanding Home Appraisals in Central Oregon'),
--   ('understanding-months-of-supply', 'Months of Supply Explained: Central Oregon, July 2026'),
--   ('vacation-rental-rules-bend-deschutes', 'Vacation Rental Rules in Bend and Deschutes County'),
--   ('vandevert-ranch-one-home-sold-in-12-months', 'Vandevert Ranch: One Sale in 12 Months. Worth It?'),
--   ('westside-vs-eastside-bend', 'Westside vs Eastside Bend: Price, Walkability, Trade-offs'),
--   ('what-happens-between-offer-accepted-and-closing', 'What Happens Between Offer Accepted and Closing Day'),
--   ('widgi-creek-condo-or-house-what-it-costs', 'Widgi Creek: Condo or House, and What Each Costs'),
--   ('working-remote-central-oregon', 'Working Remote from Central Oregon: Practical Guide')
-- ) as v(slug, seo_title) where b.slug = v.slug;
