-- CRM Inbox Drafts (FUB-parity delivery #5, spec docs/fub-crm-spec/08-inbox.md §3.3)
--
-- The Inbox "Drafts" folder shows started-but-unsent replies. Until now the
-- inbox derived every conversation from crm_timeline (sent/received messages
-- only) + the per-conversation triage state in crm_conversation_state; there was
-- no place to persist an unsent draft. This table is that store.
--
-- Model: one draft per (person, broker, channel). A broker composing a reply in
-- a thread can "Save draft"; the draft is upserted here keyed to the acting
-- broker. When the reply is actually sent (through the existing suppression-gated
-- send actions) the matching draft row is deleted. The Drafts folder lists the
-- conversations that have at least one draft owned by the acting broker.
--
-- NOTE: reads/writes go through the service-role client (lib/supabase/service),
-- same as every other crm_* table, so RLS is enabled with no public policy —
-- the service role bypasses RLS; anon/authenticated get nothing directly.

create table if not exists public.crm_message_drafts (
  id           bigint generated by default as identity primary key,
  person_id    bigint not null references public.crm_people(id) on delete cascade,
  -- The broker who owns the draft (the acting user's own slug: matt/rebecca/paul).
  -- Nullable for an unmapped admin; the unique index coalesces null to ''.
  broker_slug  text,
  channel      text not null default 'text' check (channel in ('text', 'email')),
  subject      text,                       -- email subject; null for text drafts
  body         text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- One live draft per person + broker + channel (upsert target).
create unique index if not exists crm_message_drafts_person_broker_channel_uidx
  on public.crm_message_drafts (person_id, coalesce(broker_slug, ''), channel);

-- Drafts-folder + count lookups filter by the acting broker.
create index if not exists crm_message_drafts_broker_idx
  on public.crm_message_drafts (broker_slug);

alter table public.crm_message_drafts enable row level security;

comment on table public.crm_message_drafts is
  'CRM Inbox unsent draft replies (one per person+broker+channel). Deleted on send. Service-role access only.';
