-- SITE-211: a subdivision's sold homes are read by index.
--
-- WHY. A plat's sold homes newest first, getListingTiles({ subdivision,
-- status: 'closed', sort: 'close-newest' }) in
-- lib/data/listings/getListingTiles.ts, asks listing_tile_mv for
--   subdivision_lower = <plat> AND standard_status = 'Closed'
--   ORDER BY close_date DESC NULLS LAST, listing_key ASC NULLS LAST
--   LIMIT n OFFSET m
-- (the shape of the 105 timed-out statements below; a reader that adds a
-- close_date window reads the same index range). No index led with the plat
-- for closed rows, so the planner walked listing_tile_mv_closed_recent_sold,
-- every closed sale in the region newest first, and dropped the other plats'
-- rows one by one, each read from the heap for its plat. Measured on
-- production 2026-09-30 with a 12-row page: Broken Top 0.1 s, Keystone
-- Terrace 3.0 s (76,902 rows dropped), a plat with no closed sale 8.2 s (all
-- 381,292). anon's statement_timeout is 3 s: 105 of these reads timed out in
-- the 24 hours to 23:50Z, in quiet hours as well as deploy hours, and
-- getListingTiles then falls back to no homes (the Sold split view, through
-- getListingTilesOrThrow, shows its delayed state).
--
-- THE FIX. The read's own order, one plat at a time: equality on
-- subdivision_lower, then the query's sort keys, partial on its status. The
-- walk reads the plat's newest entries and stops: Keystone Terrace 0.25 ms,
-- Broken Top 0.26 ms (93 ms for a 500-row page), a plat with no closed sale
-- 0.11 ms. Same rows in the same order (listing_key is unique, so the order
-- is total).
--
-- Applied to production 2026-09-30 with CREATE INDEX CONCURRENTLY through a
-- one-shot pg_cron job, so the build could not block the drain's writes to
-- listing_tile_mv_src; this file records the end state, and was applied
-- through the migration tool on 2026-10-01 so the history carries it (a no-op:
-- the index existed). CONCURRENTLY cannot run inside a transaction, so a
-- transactional replay runs the plain form.
CREATE INDEX IF NOT EXISTS listing_tile_mv_closed_subdivision_sold
  ON public.listing_tile_mv_src USING btree (subdivision_lower, close_date DESC NULLS LAST, listing_key)
  WHERE (standard_status = 'Closed'::text);
